site_name: Christina Schmitter   
copyright: <a href="https://choosealicense.com/licenses/mit/">License</a>
  &copy; 2023 Christina Schmitter<br>

theme:                  ##under theme goes everything design related
    name: material
    palette:
      primary: blue grey
      accent: cyan
    font:
      codes: Quicksand 
    features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.top
      - navigation.sections
      - navigation.expand
      - toc.integrate
docs_dir: docs   
nav:
  - Home: index.md
  - About: aboutme.md
  - CV: cv.md
  - Publications: publications.md    
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - codehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg  

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jk_pfarr
    - icon: fontawesome/brands/github
      link: https://github.com/julia-pfarr
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/julia-katharina-pfarr-2a6437236/
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Julia-Katharina-Pfarr
    - icon: material/email
      link: mailto:pfarr@staff.uni-marburg.de 